[project]
name = "mcp-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-groq>=0.3.2",
    "langchain-openai>=0.3.16",
    "mcp-use>=1.2.8",
    "mcp[cli]>=1.7.1",
    "ruff>=0.11.7",
]
